---
# tasks file for nginx

- name: yum install nginx
  yum:
    name: nginx
    state: present
  ignore_errors: yes
  register: yum_nginx
- name: url install nginx
  block:
    - name: download nginx-1.24.0.tar.gz
      get_url:
        url: https://nginx.org/download/nginx-1.24.0.tar.gz
        dest: /opt/
    - name: tar xzf nginx-1.24.0.tar.gz
  when: yum_nginx.failed is true
