---
# tasks file for nginx

- name: which nginx
  shell: "which nginx"
  ignore_errors: yes
  register: nginx_exist

- name: install nginx if it not installed
  include_tasks: install.yml
  when: nginx_exist.rc != 0


